type readOutConfig = {
  itIs:bool,
  hour: int,
  isExact:bool,
  isAbout: bool,
  isAfternoon: bool,
  isEvening: bool,
  isMidnight: bool,
  isMorning: bool,
  isNearly: bool,
  isNoon: bool,
  isOClock: bool,
  isPast: bool,
  isTo: bool,
  minute: int,
};